kind: pipeline
type: docker
name: build-publish-image

steps:
- name: test
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
  - go build -a -ldflags "-X main.version=${DRONE_TAG} -X main.rev=${DRONE_COMMIT}"
  - go test ./...

- name: build_publish_dev
  image: plugins/docker
  settings:
    repo: nytimes/drone-admit-members
    # auto_tag: true
    secrets:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - build
      - ${DRONE_COMMIT}
  when:
    ref:
      include:
        - refs/heads/master
      exclude:
        - refs/tags/*
  depends_on:
    - test

- name: build_publish_release
  image: plugins/docker
  settings:
    repo: nytimes/drone-admit-members
    # auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - ${DRONE_COMMIT}
      - ${DRONE_TAG}
  when:
    ref:
      - refs/heads/master
      - refs/tags/*
    branch:
      - master
  depends_on:
    - test
