kind: pipeline
type: docker
name: build-image

steps:
- name: build
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
  - go build
  - go test ./...

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: mlclmj/drone-admit-members
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
