kind: pipeline
type: docker
name: build-publish-image

steps:
- name: test
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
  - go build -a -ldflags "-X main.version=${DRONE_TAG} -X main.rev=${DRONE_COMMIT}"
  - go test ./...

- name: build_publish_unstable
  image: plugins/docker
  settings:
    repo: nytimes/drone-admit-members
    secrets:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - unstable
      - ${DRONE_COMMIT}
    build_args_from_env:
      - DRONE_TAG
      - DRONE_COMMIT
  when:
    ref:
      exclude:
        - refs/tags/*
    branch:
      - main
  depends_on:
    - test

- name: build_publish_stable
  image: plugins/docker
  settings:
    repo: nytimes/drone-admit-members
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - stable
      - ${DRONE_COMMIT}
      - ${DRONE_TAG}
    build_args_from_env:
      - DRONE_TAG
      - DRONE_COMMIT
  when:
    ref:
      - refs/tags/*
    branch:
      - main
  depends_on:
    - test
