---
apiVersion: v1
kind: Service
metadata:
  name: drone-admission
  labels:
    app.kubernetes.io/name: drone-admission
    app.kubernetes.io/instance: drone
    app.kubernetes.io/component: admission
    app.kubernetes.io/version: latest
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: drone-admission
    app.kubernetes.io/instance: drone
    app.kubernetes.io/component: admission
